### ISSUE TITLE
Support PR_SET_KEEPCAPS

### ISSUE THREAD

**Issue by kpcyrd** [lucab/caps-rs#26]
hey! I've noticed that the crate is currently not able to retain capabilities across a uid transition. It might be useful to have a function that corresponds to:

```c
prctl(PR_SET_KEEPCAPS, 1, 0, 0, 0);
```

**Comment by lucab** [comment]
Indeed. It looks like I have some background reading to do about `SECBIT_KEEP_CAPS` too.

**Comment by lucab** [comment]
I started by implementing the GET/SET for KEEPCAPS. The rest of the securebits work in a different way, so I'll follow up with a ticket to implement those later.

**Comment by lucab** [comment]
This is now released as part of [caps-0.3.0](https://docs.rs/caps/0.3.0/caps/securebits/index.html).
