### ISSUE TITLE
ambient: add ambient_set_supported()

### ISSUE THREAD

**Issue by lucab** [lucab/caps-rs#7]
This is an enhancement ticket to add run-time detection of ambient set support, which is only available on kernels >= 4.3.

The proposed signature is as follow:
```
pub fn ambient_set_supported() -> Result<(), Err(i32)>
```
(or maybe only a `bool` which just swallows all errno into `false`?)

This can be implement via `PR_CAP_AMBIENT`+`PR_CAP_AMBIENT_IS_SET`+`CAP_CHOWN` which should always return >=0 when the set is supported.

/cc @vishvananda and @aep for feedback on the ergonomic/signature. This is intended to provide a simple way for consumers to opt out ambient-set manipulation on kernels where it is unsupported: a conditional on `caps::ambient_set_supported().is_ok()`.

**Comment by aep** [comment]
not sure if bool is fine, since the caller might not have permissions. Should probably at least return an enum.
otherwise, yes please!
