### ISSUE TITLE
Release 0.5.3

### ISSUE THREAD

**Issue by luben** [lucab/caps-rs#76]
Is there any pending changes for 0.5.3? I think the `serde` support is big enough feature.

**Comment by lucab** [comment]
Nothing pending from my side, we can indeed cut a 0.5.3 release.
If you want to drive that yourself, it is usually done via [cargo-release](https://github.com/crate-ci/cargo-release) through a PR (in a way which looks like [this](https://github.com/lucab/caps-rs/pull/71)). I'll happily review/merge/publish a PR for that.

**Comment by luben** [comment]
Great! I will send review shortly

**Comment by lucab** [comment]
Closed by https://github.com/lucab/caps-rs/pull/77.
